In [1]:
from binascii import unhexlify
import numpy as np

In [4]:
x=unhexlify(bytes("003c", 'utf-8'))
np.frombuffer(x, np.float16)

array([1.], dtype=float16)

In [7]:
x=unhexlify(bytes("004e", 'utf-8'))
np.frombuffer(x, np.float16)

array([24.], dtype=float16)

In [8]:
x=unhexlify(bytes("205c", 'utf-8'))
np.frombuffer(x, np.float16)

array([264.], dtype=float16)

In [9]:
x=unhexlify(bytes("345c", 'utf-8'))
np.frombuffer(x, np.float16)

array([269.], dtype=float16)