In [26]:
from PIL import Image
import numpy as np
import cv2

In [35]:
img = Image.open("input/cat.jpg")
x = np.array(img, dtype=np.float32)
print(x.shape)

(224, 224, 3)


In [21]:
print(x[:,0,0])

[ 27.  26.  26.  28.  30.  31.  31.  30.  31.  31.  32.  32.  31.  30.
  31.  31.  32.  29.  29.  30.  31.  31.  33.  33.  32.  33.  33.  34.
  32.  31.  30.  31.  33.  32.  32.  33.  35.  34.  34.  33.  31.  32.
  32.  32.  29.  29.  29.  30.  31.  31.  31.  31.  31.  31.  28.  29.
  28.  28.  29.  29.  29.  28.  28.  27.  26.  25.  25.  26.  23.  22.
  28.  37.  46.  55.  59.  65.  78.  87.  92.  98.  98.  96.  95.  98.
 104. 107. 104. 102. 103. 102. 100. 102. 109. 113. 116. 119. 116. 116.
 114. 110. 107. 104. 101. 103. 102.  96.  99. 107. 114. 115. 113. 108.
  95.  91.  87.  85.  82.  83.  87.  90.  94. 100. 107. 109. 107. 106.
  96.  84.  75.  71.  65.  57.  65.  79.  86.  93.  80.  83.  81.  78.
  77.  83.  88.  98. 114. 123. 128. 120. 112. 112. 101. 101. 108. 107.
 102.  99.  96.  85.  81.  86.  91.  95. 103. 100.  96. 100. 100.  96.
  83.  87.  96.  99.  90.  84.  75.  97. 111. 114. 109.  98.  79.  86.
  82.  80.  77.  67.  65.  67.  82.  91.  75.  69.  64.  67.  73.  72.
  62. 

In [10]:
print(x[:,:,0].shape)

(224, 224)


In [91]:
tmp = []
channel = 3
for i in range(25):
    for j in range(channel):
        tmp.append(i)
print(tmp)

x = np.array(tmp)
x = np.reshape(x, (5,5,3))
print(x[:,:,0])

[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
cv2.imwrite("conv.jpg", x)
print("save img conv.jpg")

save img conv.jpg


In [85]:
img = cv2.imread("conv.jpg")
x = np.array(img, dtype=np.float32)
print(x.shape)
x = np.reshape(x, (1,5,5,3))
print(x.shape)

(5, 5, 3)
(1, 5, 5, 3)


In [86]:
x = np.transpose(x,(0,3,1,2))
print(x.shape)

(1, 3, 5, 5)


In [87]:
print(x.shape)
print(x)

(1, 3, 5, 5)
[[[[ 0.  1.  2.  3.  4.]
   [ 5.  6.  7.  8.  9.]
   [10. 11. 12. 13. 14.]
   [15. 16. 17. 18. 19.]
   [20. 20. 22. 23. 24.]]

  [[ 0.  1.  2.  3.  4.]
   [ 5.  6.  7.  8.  9.]
   [10. 11. 12. 13. 14.]
   [15. 16. 17. 18. 19.]
   [20. 20. 22. 23. 24.]]

  [[ 0.  1.  2.  3.  4.]
   [ 5.  6.  7.  8.  9.]
   [10. 11. 12. 13. 14.]
   [15. 16. 17. 18. 19.]
   [20. 20. 22. 23. 24.]]]]


In [90]:
img = cv2.imread("conv.jpg")
x = np.array(img, dtype=np.float32)
print(x[:,0,0])

[ 0.  5. 10. 15. 20.]
